import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const REPORT_PATH = path.resolve(
  process.cwd(),
  "../../openspec/changes/refine-web-research-visual-system/evidence/browser/matrix/matrix-report.json"
);

export default class EvidenceReporter {
  startedAt = "";
  matrixTests = 0;
  results = [];

  onBegin(_config, suite) {
    this.startedAt = new Date().toISOString();
    this.matrixTests = suite.allTests().filter((test) => test.location.file.endsWith("matrix.spec.ts")).length;
  }

  onTestEnd(test, result) {
    this.results.push({
      testId: test.id,
      title: test.titlePath().join(" > "),
      status: result.status,
      errors: result.errors.map((error) => error.message ?? String(error))
    });
  }

  async onEnd(run) {
    if (this.matrixTests === 0) return;

    const report = JSON.parse(await readFile(REPORT_PATH, "utf8"));
    if (Date.parse(report.generatedAt) < Date.parse(this.startedAt)) {
      throw new Error("Matrix evidence was not generated by this browser run");
    }

    const final = new Map(this.results.map((result) => [result.testId, result]));
    report.results = report.results.map((result) => ({
      ...result,
      status: final.get(result.testId)?.status ?? "missing",
      errors: final.get(result.testId)?.errors ?? ["Final Playwright result missing"]
    }));
    report.entries = report.entries.map((entry) => ({
      ...entry,
      status: final.get(entry.testId)?.status ?? "missing"
    }));
    report.suiteResults = this.results;
    report.runStatus = run.status;
    await writeFile(REPORT_PATH, `${JSON.stringify(report, null, 2)}\n`);

    if (report.results.length !== this.matrixTests || report.results.some((result) => result.status === "missing")) {
      throw new Error("Matrix evidence is missing a final test result");
    }
  }
}
